/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppProductsIndexRouteImport } from './routes/_app.products.index'
import { Route as AppPriceListsIndexRouteImport } from './routes/_app.price-lists.index'
import { Route as AppPaymentsIndexRouteImport } from './routes/_app.payments.index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app.orders.index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app.invoices.index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppProductsNewRouteImport } from './routes/_app.products.new'
import { Route as AppPriceListsNewRouteImport } from './routes/_app.price-lists.new'
import { Route as AppPriceListsIdRouteImport } from './routes/_app.price-lists.$id'
import { Route as AppPaymentsNewRouteImport } from './routes/_app.payments.new'
import { Route as AppPaymentsIdRouteImport } from './routes/_app.payments.$id'
import { Route as AppOrdersNewRouteImport } from './routes/_app.orders.new'
import { Route as AppOrdersIdRouteImport } from './routes/_app.orders.$id'
import { Route as AppInvoicesIdRouteImport } from './routes/_app.invoices.$id'
import { Route as AppInventoryTransferRouteImport } from './routes/_app.inventory.transfer'
import { Route as AppInventoryReceiptRouteImport } from './routes/_app.inventory.receipt'
import { Route as AppInventoryAdjustRouteImport } from './routes/_app.inventory.adjust'
import { Route as AppCustomersNewRouteImport } from './routes/_app.customers.new'
import { Route as AppCustomersIdRouteImport } from './routes/_app.customers.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceListsIndexRoute = AppPriceListsIndexRouteImport.update({
  id: '/price-lists/',
  path: '/price-lists/',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceListsNewRoute = AppPriceListsNewRouteImport.update({
  id: '/price-lists/new',
  path: '/price-lists/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceListsIdRoute = AppPriceListsIdRouteImport.update({
  id: '/price-lists/$id',
  path: '/price-lists/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsNewRoute = AppPaymentsNewRouteImport.update({
  id: '/payments/new',
  path: '/payments/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIdRoute = AppPaymentsIdRouteImport.update({
  id: '/payments/$id',
  path: '/payments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryTransferRoute = AppInventoryTransferRouteImport.update({
  id: '/inventory/transfer',
  path: '/inventory/transfer',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryReceiptRoute = AppInventoryReceiptRouteImport.update({
  id: '/inventory/receipt',
  path: '/inventory/receipt',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryAdjustRoute = AppInventoryAdjustRouteImport.update({
  id: '/inventory/adjust',
  path: '/inventory/adjust',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersNewRoute = AppCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit': typeof AppAuditRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/inventory/adjust': typeof AppInventoryAdjustRoute
  '/inventory/receipt': typeof AppInventoryReceiptRoute
  '/inventory/transfer': typeof AppInventoryTransferRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/payments/$id': typeof AppPaymentsIdRoute
  '/payments/new': typeof AppPaymentsNewRoute
  '/price-lists/$id': typeof AppPriceListsIdRoute
  '/price-lists/new': typeof AppPriceListsNewRoute
  '/products/new': typeof AppProductsNewRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/payments/': typeof AppPaymentsIndexRoute
  '/price-lists/': typeof AppPriceListsIndexRoute
  '/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit': typeof AppAuditRoute
  '/': typeof AppIndexRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/inventory/adjust': typeof AppInventoryAdjustRoute
  '/inventory/receipt': typeof AppInventoryReceiptRoute
  '/inventory/transfer': typeof AppInventoryTransferRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/payments/$id': typeof AppPaymentsIdRoute
  '/payments/new': typeof AppPaymentsNewRoute
  '/price-lists/$id': typeof AppPriceListsIdRoute
  '/price-lists/new': typeof AppPriceListsNewRoute
  '/products/new': typeof AppProductsNewRoute
  '/customers': typeof AppCustomersIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/payments': typeof AppPaymentsIndexRoute
  '/price-lists': typeof AppPriceListsIndexRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/': typeof AppIndexRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/customers/new': typeof AppCustomersNewRoute
  '/_app/inventory/adjust': typeof AppInventoryAdjustRoute
  '/_app/inventory/receipt': typeof AppInventoryReceiptRoute
  '/_app/inventory/transfer': typeof AppInventoryTransferRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/_app/payments/$id': typeof AppPaymentsIdRoute
  '/_app/payments/new': typeof AppPaymentsNewRoute
  '/_app/price-lists/$id': typeof AppPriceListsIdRoute
  '/_app/price-lists/new': typeof AppPriceListsNewRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/payments/': typeof AppPaymentsIndexRoute
  '/_app/price-lists/': typeof AppPriceListsIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/approvals'
    | '/audit'
    | '/customers/$id'
    | '/customers/new'
    | '/inventory/adjust'
    | '/inventory/receipt'
    | '/inventory/transfer'
    | '/invoices/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/$id'
    | '/payments/new'
    | '/price-lists/$id'
    | '/price-lists/new'
    | '/products/new'
    | '/customers/'
    | '/inventory/'
    | '/invoices/'
    | '/orders/'
    | '/payments/'
    | '/price-lists/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/approvals'
    | '/audit'
    | '/'
    | '/customers/$id'
    | '/customers/new'
    | '/inventory/adjust'
    | '/inventory/receipt'
    | '/inventory/transfer'
    | '/invoices/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/$id'
    | '/payments/new'
    | '/price-lists/$id'
    | '/price-lists/new'
    | '/products/new'
    | '/customers'
    | '/inventory'
    | '/invoices'
    | '/orders'
    | '/payments'
    | '/price-lists'
    | '/products'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/approvals'
    | '/_app/audit'
    | '/_app/'
    | '/_app/customers/$id'
    | '/_app/customers/new'
    | '/_app/inventory/adjust'
    | '/_app/inventory/receipt'
    | '/_app/inventory/transfer'
    | '/_app/invoices/$id'
    | '/_app/orders/$id'
    | '/_app/orders/new'
    | '/_app/payments/$id'
    | '/_app/payments/new'
    | '/_app/price-lists/$id'
    | '/_app/price-lists/new'
    | '/_app/products/new'
    | '/_app/customers/'
    | '/_app/inventory/'
    | '/_app/invoices/'
    | '/_app/orders/'
    | '/_app/payments/'
    | '/_app/price-lists/'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-lists/': {
      id: '/_app/price-lists/'
      path: '/price-lists'
      fullPath: '/price-lists/'
      preLoaderRoute: typeof AppPriceListsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/': {
      id: '/_app/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-lists/new': {
      id: '/_app/price-lists/new'
      path: '/price-lists/new'
      fullPath: '/price-lists/new'
      preLoaderRoute: typeof AppPriceListsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-lists/$id': {
      id: '/_app/price-lists/$id'
      path: '/price-lists/$id'
      fullPath: '/price-lists/$id'
      preLoaderRoute: typeof AppPriceListsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/new': {
      id: '/_app/payments/new'
      path: '/payments/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof AppPaymentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/$id': {
      id: '/_app/payments/$id'
      path: '/payments/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof AppPaymentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/transfer': {
      id: '/_app/inventory/transfer'
      path: '/inventory/transfer'
      fullPath: '/inventory/transfer'
      preLoaderRoute: typeof AppInventoryTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/receipt': {
      id: '/_app/inventory/receipt'
      path: '/inventory/receipt'
      fullPath: '/inventory/receipt'
      preLoaderRoute: typeof AppInventoryReceiptRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/adjust': {
      id: '/_app/inventory/adjust'
      path: '/inventory/adjust'
      fullPath: '/inventory/adjust'
      preLoaderRoute: typeof AppInventoryAdjustRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/new': {
      id: '/_app/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AppCustomersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppCustomersNewRoute: typeof AppCustomersNewRoute
  AppInventoryAdjustRoute: typeof AppInventoryAdjustRoute
  AppInventoryReceiptRoute: typeof AppInventoryReceiptRoute
  AppInventoryTransferRoute: typeof AppInventoryTransferRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppPaymentsIdRoute: typeof AppPaymentsIdRoute
  AppPaymentsNewRoute: typeof AppPaymentsNewRoute
  AppPriceListsIdRoute: typeof AppPriceListsIdRoute
  AppPriceListsNewRoute: typeof AppPriceListsNewRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppPriceListsIndexRoute: typeof AppPriceListsIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditRoute: AppAuditRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppCustomersNewRoute: AppCustomersNewRoute,
  AppInventoryAdjustRoute: AppInventoryAdjustRoute,
  AppInventoryReceiptRoute: AppInventoryReceiptRoute,
  AppInventoryTransferRoute: AppInventoryTransferRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppPaymentsIdRoute: AppPaymentsIdRoute,
  AppPaymentsNewRoute: AppPaymentsNewRoute,
  AppPriceListsIdRoute: AppPriceListsIdRoute,
  AppPriceListsNewRoute: AppPriceListsNewRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppPriceListsIndexRoute: AppPriceListsIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
