/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppWarehousesIndexRouteImport } from './routes/_app.warehouses.index'
import { Route as AppUsersIndexRouteImport } from './routes/_app.users.index'
import { Route as AppProductsIndexRouteImport } from './routes/_app.products.index'
import { Route as AppPriceListsIndexRouteImport } from './routes/_app.price-lists.index'
import { Route as AppPaymentsIndexRouteImport } from './routes/_app.payments.index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app.orders.index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app.invoices.index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppAccountingIndexRouteImport } from './routes/_app.accounting.index'
import { Route as AppWarehousesIdRouteImport } from './routes/_app.warehouses.$id'
import { Route as AppUsersIdRouteImport } from './routes/_app.users.$id'
import { Route as AppProductsNewRouteImport } from './routes/_app.products.new'
import { Route as AppProductsIdRouteImport } from './routes/_app.products.$id'
import { Route as AppPriceListsNewRouteImport } from './routes/_app.price-lists.new'
import { Route as AppPriceListsIdRouteImport } from './routes/_app.price-lists.$id'
import { Route as AppPaymentsNewRouteImport } from './routes/_app.payments.new'
import { Route as AppPaymentsIdRouteImport } from './routes/_app.payments.$id'
import { Route as AppOrdersNewRouteImport } from './routes/_app.orders.new'
import { Route as AppOrdersIdRouteImport } from './routes/_app.orders.$id'
import { Route as AppInvoicesIdRouteImport } from './routes/_app.invoices.$id'
import { Route as AppInventoryTransferRouteImport } from './routes/_app.inventory.transfer'
import { Route as AppInventoryReceiptRouteImport } from './routes/_app.inventory.receipt'
import { Route as AppInventoryAdjustRouteImport } from './routes/_app.inventory.adjust'
import { Route as AppCustomersNewRouteImport } from './routes/_app.customers.new'
import { Route as AppCustomersIdRouteImport } from './routes/_app.customers.$id'
import { Route as AppAccountingTrialBalanceRouteImport } from './routes/_app.accounting.trial-balance'
import { Route as AppAccountingCoaRouteImport } from './routes/_app.accounting.coa'
import { Route as AppAccountingJournalsIndexRouteImport } from './routes/_app.accounting.journals.index'
import { Route as AppAccountingJournalsNewRouteImport } from './routes/_app.accounting.journals.new'
import { Route as AppAccountingJournalsIdRouteImport } from './routes/_app.accounting.journals.$id'
import { Route as AppAccountingAccountIdRouteImport } from './routes/_app.accounting.account.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehousesIndexRoute = AppWarehousesIndexRouteImport.update({
  id: '/warehouses/',
  path: '/warehouses/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceListsIndexRoute = AppPriceListsIndexRouteImport.update({
  id: '/price-lists/',
  path: '/price-lists/',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingIndexRoute = AppAccountingIndexRouteImport.update({
  id: '/accounting/',
  path: '/accounting/',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehousesIdRoute = AppWarehousesIdRouteImport.update({
  id: '/warehouses/$id',
  path: '/warehouses/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIdRoute = AppUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceListsNewRoute = AppPriceListsNewRouteImport.update({
  id: '/price-lists/new',
  path: '/price-lists/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceListsIdRoute = AppPriceListsIdRouteImport.update({
  id: '/price-lists/$id',
  path: '/price-lists/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsNewRoute = AppPaymentsNewRouteImport.update({
  id: '/payments/new',
  path: '/payments/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIdRoute = AppPaymentsIdRouteImport.update({
  id: '/payments/$id',
  path: '/payments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryTransferRoute = AppInventoryTransferRouteImport.update({
  id: '/inventory/transfer',
  path: '/inventory/transfer',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryReceiptRoute = AppInventoryReceiptRouteImport.update({
  id: '/inventory/receipt',
  path: '/inventory/receipt',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryAdjustRoute = AppInventoryAdjustRouteImport.update({
  id: '/inventory/adjust',
  path: '/inventory/adjust',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersNewRoute = AppCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingTrialBalanceRoute =
  AppAccountingTrialBalanceRouteImport.update({
    id: '/accounting/trial-balance',
    path: '/accounting/trial-balance',
    getParentRoute: () => AppRoute,
  } as any)
const AppAccountingCoaRoute = AppAccountingCoaRouteImport.update({
  id: '/accounting/coa',
  path: '/accounting/coa',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingJournalsIndexRoute =
  AppAccountingJournalsIndexRouteImport.update({
    id: '/accounting/journals/',
    path: '/accounting/journals/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAccountingJournalsNewRoute =
  AppAccountingJournalsNewRouteImport.update({
    id: '/accounting/journals/new',
    path: '/accounting/journals/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppAccountingJournalsIdRoute = AppAccountingJournalsIdRouteImport.update({
  id: '/accounting/journals/$id',
  path: '/accounting/journals/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingAccountIdRoute = AppAccountingAccountIdRouteImport.update({
  id: '/accounting/account/$id',
  path: '/accounting/account/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit': typeof AppAuditRoute
  '/accounting/coa': typeof AppAccountingCoaRoute
  '/accounting/trial-balance': typeof AppAccountingTrialBalanceRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/inventory/adjust': typeof AppInventoryAdjustRoute
  '/inventory/receipt': typeof AppInventoryReceiptRoute
  '/inventory/transfer': typeof AppInventoryTransferRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/payments/$id': typeof AppPaymentsIdRoute
  '/payments/new': typeof AppPaymentsNewRoute
  '/price-lists/$id': typeof AppPriceListsIdRoute
  '/price-lists/new': typeof AppPriceListsNewRoute
  '/products/$id': typeof AppProductsIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/users/$id': typeof AppUsersIdRoute
  '/warehouses/$id': typeof AppWarehousesIdRoute
  '/accounting/': typeof AppAccountingIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/payments/': typeof AppPaymentsIndexRoute
  '/price-lists/': typeof AppPriceListsIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/warehouses/': typeof AppWarehousesIndexRoute
  '/accounting/account/$id': typeof AppAccountingAccountIdRoute
  '/accounting/journals/$id': typeof AppAccountingJournalsIdRoute
  '/accounting/journals/new': typeof AppAccountingJournalsNewRoute
  '/accounting/journals/': typeof AppAccountingJournalsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit': typeof AppAuditRoute
  '/': typeof AppIndexRoute
  '/accounting/coa': typeof AppAccountingCoaRoute
  '/accounting/trial-balance': typeof AppAccountingTrialBalanceRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/inventory/adjust': typeof AppInventoryAdjustRoute
  '/inventory/receipt': typeof AppInventoryReceiptRoute
  '/inventory/transfer': typeof AppInventoryTransferRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/payments/$id': typeof AppPaymentsIdRoute
  '/payments/new': typeof AppPaymentsNewRoute
  '/price-lists/$id': typeof AppPriceListsIdRoute
  '/price-lists/new': typeof AppPriceListsNewRoute
  '/products/$id': typeof AppProductsIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/users/$id': typeof AppUsersIdRoute
  '/warehouses/$id': typeof AppWarehousesIdRoute
  '/accounting': typeof AppAccountingIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/payments': typeof AppPaymentsIndexRoute
  '/price-lists': typeof AppPriceListsIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/warehouses': typeof AppWarehousesIndexRoute
  '/accounting/account/$id': typeof AppAccountingAccountIdRoute
  '/accounting/journals/$id': typeof AppAccountingJournalsIdRoute
  '/accounting/journals/new': typeof AppAccountingJournalsNewRoute
  '/accounting/journals': typeof AppAccountingJournalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounting/coa': typeof AppAccountingCoaRoute
  '/_app/accounting/trial-balance': typeof AppAccountingTrialBalanceRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/customers/new': typeof AppCustomersNewRoute
  '/_app/inventory/adjust': typeof AppInventoryAdjustRoute
  '/_app/inventory/receipt': typeof AppInventoryReceiptRoute
  '/_app/inventory/transfer': typeof AppInventoryTransferRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/_app/payments/$id': typeof AppPaymentsIdRoute
  '/_app/payments/new': typeof AppPaymentsNewRoute
  '/_app/price-lists/$id': typeof AppPriceListsIdRoute
  '/_app/price-lists/new': typeof AppPriceListsNewRoute
  '/_app/products/$id': typeof AppProductsIdRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/users/$id': typeof AppUsersIdRoute
  '/_app/warehouses/$id': typeof AppWarehousesIdRoute
  '/_app/accounting/': typeof AppAccountingIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/payments/': typeof AppPaymentsIndexRoute
  '/_app/price-lists/': typeof AppPriceListsIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/warehouses/': typeof AppWarehousesIndexRoute
  '/_app/accounting/account/$id': typeof AppAccountingAccountIdRoute
  '/_app/accounting/journals/$id': typeof AppAccountingJournalsIdRoute
  '/_app/accounting/journals/new': typeof AppAccountingJournalsNewRoute
  '/_app/accounting/journals/': typeof AppAccountingJournalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/approvals'
    | '/audit'
    | '/accounting/coa'
    | '/accounting/trial-balance'
    | '/customers/$id'
    | '/customers/new'
    | '/inventory/adjust'
    | '/inventory/receipt'
    | '/inventory/transfer'
    | '/invoices/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/$id'
    | '/payments/new'
    | '/price-lists/$id'
    | '/price-lists/new'
    | '/products/$id'
    | '/products/new'
    | '/users/$id'
    | '/warehouses/$id'
    | '/accounting/'
    | '/customers/'
    | '/inventory/'
    | '/invoices/'
    | '/orders/'
    | '/payments/'
    | '/price-lists/'
    | '/products/'
    | '/users/'
    | '/warehouses/'
    | '/accounting/account/$id'
    | '/accounting/journals/$id'
    | '/accounting/journals/new'
    | '/accounting/journals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/approvals'
    | '/audit'
    | '/'
    | '/accounting/coa'
    | '/accounting/trial-balance'
    | '/customers/$id'
    | '/customers/new'
    | '/inventory/adjust'
    | '/inventory/receipt'
    | '/inventory/transfer'
    | '/invoices/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/$id'
    | '/payments/new'
    | '/price-lists/$id'
    | '/price-lists/new'
    | '/products/$id'
    | '/products/new'
    | '/users/$id'
    | '/warehouses/$id'
    | '/accounting'
    | '/customers'
    | '/inventory'
    | '/invoices'
    | '/orders'
    | '/payments'
    | '/price-lists'
    | '/products'
    | '/users'
    | '/warehouses'
    | '/accounting/account/$id'
    | '/accounting/journals/$id'
    | '/accounting/journals/new'
    | '/accounting/journals'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/approvals'
    | '/_app/audit'
    | '/_app/'
    | '/_app/accounting/coa'
    | '/_app/accounting/trial-balance'
    | '/_app/customers/$id'
    | '/_app/customers/new'
    | '/_app/inventory/adjust'
    | '/_app/inventory/receipt'
    | '/_app/inventory/transfer'
    | '/_app/invoices/$id'
    | '/_app/orders/$id'
    | '/_app/orders/new'
    | '/_app/payments/$id'
    | '/_app/payments/new'
    | '/_app/price-lists/$id'
    | '/_app/price-lists/new'
    | '/_app/products/$id'
    | '/_app/products/new'
    | '/_app/users/$id'
    | '/_app/warehouses/$id'
    | '/_app/accounting/'
    | '/_app/customers/'
    | '/_app/inventory/'
    | '/_app/invoices/'
    | '/_app/orders/'
    | '/_app/payments/'
    | '/_app/price-lists/'
    | '/_app/products/'
    | '/_app/users/'
    | '/_app/warehouses/'
    | '/_app/accounting/account/$id'
    | '/_app/accounting/journals/$id'
    | '/_app/accounting/journals/new'
    | '/_app/accounting/journals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warehouses/': {
      id: '/_app/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof AppWarehousesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-lists/': {
      id: '/_app/price-lists/'
      path: '/price-lists'
      fullPath: '/price-lists/'
      preLoaderRoute: typeof AppPriceListsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/': {
      id: '/_app/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/': {
      id: '/_app/accounting/'
      path: '/accounting'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AppAccountingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warehouses/$id': {
      id: '/_app/warehouses/$id'
      path: '/warehouses/$id'
      fullPath: '/warehouses/$id'
      preLoaderRoute: typeof AppWarehousesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$id': {
      id: '/_app/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AppUsersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-lists/new': {
      id: '/_app/price-lists/new'
      path: '/price-lists/new'
      fullPath: '/price-lists/new'
      preLoaderRoute: typeof AppPriceListsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-lists/$id': {
      id: '/_app/price-lists/$id'
      path: '/price-lists/$id'
      fullPath: '/price-lists/$id'
      preLoaderRoute: typeof AppPriceListsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/new': {
      id: '/_app/payments/new'
      path: '/payments/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof AppPaymentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/$id': {
      id: '/_app/payments/$id'
      path: '/payments/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof AppPaymentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/transfer': {
      id: '/_app/inventory/transfer'
      path: '/inventory/transfer'
      fullPath: '/inventory/transfer'
      preLoaderRoute: typeof AppInventoryTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/receipt': {
      id: '/_app/inventory/receipt'
      path: '/inventory/receipt'
      fullPath: '/inventory/receipt'
      preLoaderRoute: typeof AppInventoryReceiptRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/adjust': {
      id: '/_app/inventory/adjust'
      path: '/inventory/adjust'
      fullPath: '/inventory/adjust'
      preLoaderRoute: typeof AppInventoryAdjustRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/new': {
      id: '/_app/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AppCustomersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/trial-balance': {
      id: '/_app/accounting/trial-balance'
      path: '/accounting/trial-balance'
      fullPath: '/accounting/trial-balance'
      preLoaderRoute: typeof AppAccountingTrialBalanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/coa': {
      id: '/_app/accounting/coa'
      path: '/accounting/coa'
      fullPath: '/accounting/coa'
      preLoaderRoute: typeof AppAccountingCoaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/journals/': {
      id: '/_app/accounting/journals/'
      path: '/accounting/journals'
      fullPath: '/accounting/journals/'
      preLoaderRoute: typeof AppAccountingJournalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/journals/new': {
      id: '/_app/accounting/journals/new'
      path: '/accounting/journals/new'
      fullPath: '/accounting/journals/new'
      preLoaderRoute: typeof AppAccountingJournalsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/journals/$id': {
      id: '/_app/accounting/journals/$id'
      path: '/accounting/journals/$id'
      fullPath: '/accounting/journals/$id'
      preLoaderRoute: typeof AppAccountingJournalsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/account/$id': {
      id: '/_app/accounting/account/$id'
      path: '/accounting/account/$id'
      fullPath: '/accounting/account/$id'
      preLoaderRoute: typeof AppAccountingAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountingCoaRoute: typeof AppAccountingCoaRoute
  AppAccountingTrialBalanceRoute: typeof AppAccountingTrialBalanceRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppCustomersNewRoute: typeof AppCustomersNewRoute
  AppInventoryAdjustRoute: typeof AppInventoryAdjustRoute
  AppInventoryReceiptRoute: typeof AppInventoryReceiptRoute
  AppInventoryTransferRoute: typeof AppInventoryTransferRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppPaymentsIdRoute: typeof AppPaymentsIdRoute
  AppPaymentsNewRoute: typeof AppPaymentsNewRoute
  AppPriceListsIdRoute: typeof AppPriceListsIdRoute
  AppPriceListsNewRoute: typeof AppPriceListsNewRoute
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppUsersIdRoute: typeof AppUsersIdRoute
  AppWarehousesIdRoute: typeof AppWarehousesIdRoute
  AppAccountingIndexRoute: typeof AppAccountingIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppPriceListsIndexRoute: typeof AppPriceListsIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppWarehousesIndexRoute: typeof AppWarehousesIndexRoute
  AppAccountingAccountIdRoute: typeof AppAccountingAccountIdRoute
  AppAccountingJournalsIdRoute: typeof AppAccountingJournalsIdRoute
  AppAccountingJournalsNewRoute: typeof AppAccountingJournalsNewRoute
  AppAccountingJournalsIndexRoute: typeof AppAccountingJournalsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditRoute: AppAuditRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountingCoaRoute: AppAccountingCoaRoute,
  AppAccountingTrialBalanceRoute: AppAccountingTrialBalanceRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppCustomersNewRoute: AppCustomersNewRoute,
  AppInventoryAdjustRoute: AppInventoryAdjustRoute,
  AppInventoryReceiptRoute: AppInventoryReceiptRoute,
  AppInventoryTransferRoute: AppInventoryTransferRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppPaymentsIdRoute: AppPaymentsIdRoute,
  AppPaymentsNewRoute: AppPaymentsNewRoute,
  AppPriceListsIdRoute: AppPriceListsIdRoute,
  AppPriceListsNewRoute: AppPriceListsNewRoute,
  AppProductsIdRoute: AppProductsIdRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppUsersIdRoute: AppUsersIdRoute,
  AppWarehousesIdRoute: AppWarehousesIdRoute,
  AppAccountingIndexRoute: AppAccountingIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppPriceListsIndexRoute: AppPriceListsIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppWarehousesIndexRoute: AppWarehousesIndexRoute,
  AppAccountingAccountIdRoute: AppAccountingAccountIdRoute,
  AppAccountingJournalsIdRoute: AppAccountingJournalsIdRoute,
  AppAccountingJournalsNewRoute: AppAccountingJournalsNewRoute,
  AppAccountingJournalsIndexRoute: AppAccountingJournalsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
