/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppProductsIndexRouteImport } from './routes/_app.products.index'
import { Route as AppPaymentsIndexRouteImport } from './routes/_app.payments.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppProductsNewRouteImport } from './routes/_app.products.new'
import { Route as AppPaymentsNewRouteImport } from './routes/_app.payments.new'
import { Route as AppPaymentsIdRouteImport } from './routes/_app.payments.$id'
import { Route as AppOrdersNewRouteImport } from './routes/_app.orders.new'
import { Route as AppOrdersIdRouteImport } from './routes/_app.orders.$id'
import { Route as AppInvoicesIdRouteImport } from './routes/_app.invoices.$id'
import { Route as AppInventoryReceiptRouteImport } from './routes/_app.inventory.receipt'
import { Route as AppCustomersNewRouteImport } from './routes/_app.customers.new'
import { Route as AppCustomersIdRouteImport } from './routes/_app.customers.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsNewRoute = AppPaymentsNewRouteImport.update({
  id: '/payments/new',
  path: '/payments/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIdRoute = AppPaymentsIdRouteImport.update({
  id: '/payments/$id',
  path: '/payments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInventoryReceiptRoute = AppInventoryReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppCustomersNewRoute = AppCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AppApprovalsRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/invoices': typeof AppInvoicesRouteWithChildren
  '/orders': typeof AppOrdersRouteWithChildren
  '/customers/$id': typeof AppCustomersIdRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/inventory/receipt': typeof AppInventoryReceiptRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/payments/$id': typeof AppPaymentsIdRoute
  '/payments/new': typeof AppPaymentsNewRoute
  '/products/new': typeof AppProductsNewRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/payments/': typeof AppPaymentsIndexRoute
  '/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/approvals': typeof AppApprovalsRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/invoices': typeof AppInvoicesRouteWithChildren
  '/orders': typeof AppOrdersRouteWithChildren
  '/': typeof AppIndexRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/inventory/receipt': typeof AppInventoryReceiptRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/payments/$id': typeof AppPaymentsIdRoute
  '/payments/new': typeof AppPaymentsNewRoute
  '/products/new': typeof AppProductsNewRoute
  '/customers': typeof AppCustomersIndexRoute
  '/payments': typeof AppPaymentsIndexRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/invoices': typeof AppInvoicesRouteWithChildren
  '/_app/orders': typeof AppOrdersRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/customers/new': typeof AppCustomersNewRoute
  '/_app/inventory/receipt': typeof AppInventoryReceiptRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/_app/payments/$id': typeof AppPaymentsIdRoute
  '/_app/payments/new': typeof AppPaymentsNewRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/payments/': typeof AppPaymentsIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/approvals'
    | '/inventory'
    | '/invoices'
    | '/orders'
    | '/customers/$id'
    | '/customers/new'
    | '/inventory/receipt'
    | '/invoices/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/$id'
    | '/payments/new'
    | '/products/new'
    | '/customers/'
    | '/payments/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/approvals'
    | '/inventory'
    | '/invoices'
    | '/orders'
    | '/'
    | '/customers/$id'
    | '/customers/new'
    | '/inventory/receipt'
    | '/invoices/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/$id'
    | '/payments/new'
    | '/products/new'
    | '/customers'
    | '/payments'
    | '/products'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/approvals'
    | '/_app/inventory'
    | '/_app/invoices'
    | '/_app/orders'
    | '/_app/'
    | '/_app/customers/$id'
    | '/_app/customers/new'
    | '/_app/inventory/receipt'
    | '/_app/invoices/$id'
    | '/_app/orders/$id'
    | '/_app/orders/new'
    | '/_app/payments/$id'
    | '/_app/payments/new'
    | '/_app/products/new'
    | '/_app/customers/'
    | '/_app/payments/'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/': {
      id: '/_app/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/new': {
      id: '/_app/payments/new'
      path: '/payments/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof AppPaymentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/$id': {
      id: '/_app/payments/$id'
      path: '/payments/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof AppPaymentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/inventory/receipt': {
      id: '/_app/inventory/receipt'
      path: '/receipt'
      fullPath: '/inventory/receipt'
      preLoaderRoute: typeof AppInventoryReceiptRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/customers/new': {
      id: '/_app/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AppCustomersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppInventoryRouteChildren {
  AppInventoryReceiptRoute: typeof AppInventoryReceiptRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryReceiptRoute: AppInventoryReceiptRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppInvoicesRouteChildren {
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
}

const AppInvoicesRouteChildren: AppInvoicesRouteChildren = {
  AppInvoicesIdRoute: AppInvoicesIdRoute,
}

const AppInvoicesRouteWithChildren = AppInvoicesRoute._addFileChildren(
  AppInvoicesRouteChildren,
)

interface AppOrdersRouteChildren {
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
}

const AppOrdersRouteChildren: AppOrdersRouteChildren = {
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
}

const AppOrdersRouteWithChildren = AppOrdersRoute._addFileChildren(
  AppOrdersRouteChildren,
)

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppInvoicesRoute: typeof AppInvoicesRouteWithChildren
  AppOrdersRoute: typeof AppOrdersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppCustomersNewRoute: typeof AppCustomersNewRoute
  AppPaymentsIdRoute: typeof AppPaymentsIdRoute
  AppPaymentsNewRoute: typeof AppPaymentsNewRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppInvoicesRoute: AppInvoicesRouteWithChildren,
  AppOrdersRoute: AppOrdersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppCustomersNewRoute: AppCustomersNewRoute,
  AppPaymentsIdRoute: AppPaymentsIdRoute,
  AppPaymentsNewRoute: AppPaymentsNewRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
